package com.example.dto;

import java.math.BigDecimal;
import java.util.UUID;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * Generated DTO class for ${dto.name}
 * Generated by Eventor Spring Event Generator
 */
public class ${dto.name} {

<#list dto.fields as fieldName, fieldType>
    private ${fieldType} ${fieldName};
</#list>

    public ${dto.name}() {}

    public ${dto.name}(<#list dto.fields as fieldName, fieldType>${fieldType} ${fieldName}<#if fieldName_has_next>, </#if></#list>) {
<#list dto.fields as fieldName, fieldType>
        this.${fieldName} = ${fieldName};
</#list>
    }

<#list dto.fields as fieldName, fieldType>
    public ${fieldType} get${fieldName?cap_first}() {
        return ${fieldName};
    }

    public void set${fieldName?cap_first}(${fieldType} ${fieldName}) {
        this.${fieldName} = ${fieldName};
    }

</#list>
    @Override
    public String toString() {
        return "${dto.name}{" +
<#list dto.fields as fieldName, fieldType>
                "${fieldName}=" + ${fieldName} +<#if fieldName_has_next>
<#else>
                '}';
</#if>
</#list>
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ${dto.name} that = (${dto.name}) o;
        return java.util.Objects.equals(<#list dto.fields as fieldName, fieldType>${fieldName}<#if fieldName_has_next>, that.${fieldName}) &&
               java.util.Objects.equals(<#else>, that.${fieldName});
</#if></#list>
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(<#list dto.fields as fieldName, fieldType>${fieldName}<#if fieldName_has_next>, </#if></#list>);
    }
}
