package com.example.producer;

import com.example.dto.${producer.dto};
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.stereotype.Component;

/**
 * Generated Producer class for ${producer.name}
 * Generated by Eventry Spring Event Generator
 */
@Component
public class ${producer.name} {

    private final KafkaTemplate<String, ${producer.dto}> ${producer.factoryBean};

    @Autowired
    public ${producer.name}(KafkaTemplate<String, ${producer.dto}> ${producer.factoryBean}) {
        this.${producer.factoryBean} = ${producer.factoryBean};
    }

    /**
     * Sends ${producer.dto} to ${producer.topic} topic
     * @param event the event to send
     */
    public void send${producer.dto}(${producer.dto} event) {
        ${producer.factoryBean}.send("${producer.topic}", event);
    }

    /**
     * Sends ${producer.dto} to ${producer.topic} topic with specific key
     * @param key the partition key
     * @param event the event to send
     */
    public void send${producer.dto}(String key, ${producer.dto} event) {
        ${producer.factoryBean}.send("${producer.topic}", key, event);
    }
}
